version: '3.7'
services:
    db:
        build:
          context: .
          dockerfile: ./docker/PostgresDockerfile
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgres/postgres_data:/var/lib/postgresql
        networks:
            - ticketflow-network
        restart: unless-stopped
        ports:
            - 5432:5432
          
    eureka-server:
        image: darkmode1012/ticketflow:eureka-server
        build:
            context: .
            dockerfile: ./docker/EurekaServerDockerfile
        networks:
            - ticketflow-network
        restart: unless-stopped
        ports:
            - 8761:8761
          
    rabbitmq:
        image: "rabbitmq:3"
        networks:
            - ticketflow-network
        ports:
            - 15672:15672
            - 5672:5672
      
    config-server:
        image: darkmode1012/ticketflow:config-server
        build:
            context: .
            dockerfile: ./docker/ConfigServerDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - eureka-server
            - rabbitmq
        restart: unless-stopped
        ports:
            - 8888:8888
        entrypoint: ["/app/wait-for-it.sh", "rabbitmq:5672", "-t", "60", "--", 
                    "/app/wait-for-it.sh", "eureka-server:8761", "-t", "60", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

    identity-service:
        image: darkmode1012/ticketflow:identity-service
        build:
            context: .
            dockerfile: ./docker/IdentityServiceDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - db
            - eureka-server
            - config-server
            - rabbitmq
        restart: unless-stopped
        entrypoint: ["/app/wait-for-it.sh", "config-server:8888", "-t", "120", "--",
                    "/app/wait-for-it.sh", "db:5432", "-t", "120", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

    profile-service:
        image: darkmode1012/ticketflow:profile-service
        build:
            context: .
            dockerfile: ./docker/ProfileServiceDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - db
            - eureka-server
            - config-server
            - rabbitmq
        restart: unless-stopped
        entrypoint: ["/app/wait-for-it.sh", "config-server:8888", "-t", "120", "--",
                    "/app/wait-for-it.sh", "db:5432", "-t", "120", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

    ticket-service:
        image: darkmode1012/ticketflow:ticket-service
        build:
            context: .
            dockerfile: ./docker/TicketServiceDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - db
            - eureka-server
            - config-server
            - rabbitmq
        restart: unless-stopped
        entrypoint: ["/app/wait-for-it.sh", "config-server:8888", "-t", "120", "--",
                    "/app/wait-for-it.sh", "db:5432", "-t", "120", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

    movie-service:
        image: darkmode1012/ticketflow:movie-service
        build:
            context: .
            dockerfile: ./docker/MovieServiceDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - db
            - eureka-server
            - config-server
            - rabbitmq
        restart: unless-stopped            
        entrypoint: ["/app/wait-for-it.sh", "config-server:8888", "-t", "120", "--",
                    "/app/wait-for-it.sh", "db:5432", "-t", "120", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

    api-gateway:
        image: darkmode1012/ticketflow:api-gateway
        build:
            context: .
            dockerfile: ./docker/ApiGatewayDockerfile
        networks:
            - ticketflow-network
        depends_on:
            - eureka-server
            - rabbitmq
            - config-server
            - identity-service
            - profile-service
            - ticket-service
            - movie-service
        ports:
            - 8080:8080
        restart: unless-stopped
        entrypoint: ["/app/wait-for-it.sh", "identity-service:9001", "-t", "180", "--",
                    "/app/wait-for-it.sh", "profile-service:9002", "-t", "180", "--",
                    "/app/wait-for-it.sh", "ticket-service:9003", "-t", "180", "--",
                    "/app/wait-for-it.sh", "movie-service:9004", "-t", "180", "--",
                    "java", "-jar", "/app/spring-boot-application.jar"]

networks: 
  ticketflow-network:
    driver: bridge